version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: harley-umbrel-mimic3_server_1
      APP_PORT: 59125
      PROXY_AUTH_ADD: 'true'
  server:
    image: mycroftai/mimic3:0.2.4
    restart: on-failure
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/home/mimic3/.local/share/mycroft/mimic3
      - ${APP_DATA_DIR}/download.py:/home/mimic3/app/mimic3_tts/download.py
      - ${APP_DATA_DIR}/const.py:/home/mimic3/app/mimic3_tts/const.py
    ports:
      - 59125:59125/udp
    tty: true
    stdin_open: true
