version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: harley-umbrel-mimic3_server_1
      APP_PORT: 59125
      PROXY_AUTH_ADD: 'true'
    container_name: harley-umbrel-mimic3_app_proxy_1
  server:
    image: mycroftai/mimic3:0.2.4
    restart: on-failure
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/home/mimic3/.local/share/mycroft/mimic3
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 59125:59125/udp
    tty: true
    stdin_open: true
