version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: harley-umbrel-opentts_server_1
      APP_PORT: 5500
      PROXY_AUTH_ADD: "true"

  server:
    image: synesthesiam/opentts:en-2.1
    restart: unless-stopped
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/cache:/cache
    ports:
      # Service auto-discovery
      - 5500:5500/udp
