version: "3.7"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: harley-umbrel-piper-hub_server_1
      APP_PORT: 5000
      PROXY_AUTH_ADD: 'true'
  server:
    image: hlappano/piper-hub:v1.1.1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    ports:
      - 5000:5000/udp # Flask Web Service
