version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: harley-umbrel-actualbudget_server_1
      APP_PORT: 5006
      PROXY_AUTH_ADD: "false"

  server:
    image: actualbudget/actual-server:25.1.0
    restart: unless-stopped
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/actual-data:/data
    ports:
      - 5006:5006

# See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
